### PR TITLE
More Revolutionary Factions

### PR DESCRIPTION
**Pull request by awandke**
This merge would create an option for both Lothlorien and Rivendell to create their own revolutionary factions. I think this will make a playthrough more fun for players seeking to play revolutionary on these nations, especially if they are playing in multiplayer. 

Rivendell currently can create unique belligerent, unaligned, and cooperative factions, but not a revolutionary one. This adds that as a feature. I have implemented this with a new focus called "Global Collective" to create a faction called "Global Collective". 

Lothlorien likewise can create custom belligerent and cooperative factions, but not a revolutionary one (unaligned faction probably does not make sense for Lothlorien and they can maybe join Rivendell collective). Since I did not think there was not an obvious place to add this to the Lothlorien tree, I've simply added the "can_create_factions = yes" on "Galadriel's farewell" focus. 

Open to any suggestions/improvements. Is "Global Collective" a good name?

image
image

### CODE REVIEW

**Comment by Helliaca** [comment]
I agree overall.

Though imo having it in "Galadriel's Farewell" is a bit too early. I think the "A Shared Cause" focus would be a lot more fitting, especially since that one is fairly useless in most situations anyway.

**Comment by awandke** [comment]
good idea :)

**Comment by awandke** [comment]
It also just occurred to me that it would also be fun to have a hobbit communist faction.

**Comment by Helliaca** [comment]
Looks good to me. Thanks again!

**Pull request merged**
